"""empty message

Revision ID: 149adf8954ef
Revises: b76b83a114bb
Create Date: 2020-03-10 10:26:40.029000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149adf8954ef'
down_revision = 'b76b83a114bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('university_picture', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'university_picture')
    # ### end Alembic commands ###
