"""empty message

Revision ID: 3224ea33a8e9
Revises: 7a794ab9febb
Create Date: 2020-02-29 12:39:11.770000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3224ea33a8e9'
down_revision = '7a794ab9febb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('univer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['univer_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logo')
    # ### end Alembic commands ###
