"""empty message

Revision ID: 3de1cc85d9ea
Revises: cf10e185cfbc
Create Date: 2020-03-13 11:59:39.619000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3de1cc85d9ea'
down_revision = 'cf10e185cfbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'desc')
    op.add_column('university', sa.Column('desc', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'desc')
    op.add_column('department', sa.Column('desc', mysql.VARCHAR(length=1000), nullable=True))
    # ### end Alembic commands ###
