"""empty message

Revision ID: 7a794ab9febb
Revises: 7ce04814b9b7
Create Date: 2020-02-28 22:52:00.672000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a794ab9febb'
down_revision = '7ce04814b9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'university', 'state', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'university', type_='foreignkey')
    op.drop_column('university', 'state_id')
    # ### end Alembic commands ###
