"""empty message

Revision ID: 7ce04814b9b7
Revises: 298df315b5d3
Create Date: 2020-02-28 17:10:03.104000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce04814b9b7'
down_revision = '298df315b5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('department', sa.Column('degree', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('price', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'department', 'degree', ['degree'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department', type_='foreignkey')
    op.drop_column('department', 'price')
    op.drop_column('department', 'duration')
    op.drop_column('department', 'degree')
    op.drop_table('degree')
    # ### end Alembic commands ###
