"""empty message

Revision ID: a525b4bb28e6
Revises: e409a6f34723
Create Date: 2020-03-12 17:52:58.655000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a525b4bb28e6'
down_revision = 'e409a6f34723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('flag', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('country', 'flag')
    # ### end Alembic commands ###
