"""empty message

Revision ID: cf10e185cfbc
Revises: a525b4bb28e6
Create Date: 2020-03-13 11:58:30.807000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf10e185cfbc'
down_revision = 'a525b4bb28e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('desc', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'desc')
    # ### end Alembic commands ###
