"""empty message

Revision ID: e409a6f34723
Revises: d4a3042c9508
Create Date: 2020-03-11 10:52:58.442000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e409a6f34723'
down_revision = 'd4a3042c9508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('international_universities', sa.Column('country', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'international_universities', 'country', ['country'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'international_universities', type_='foreignkey')
    op.drop_column('international_universities', 'country')
    op.drop_table('country')
    # ### end Alembic commands ###
